### DISCUSSION TITLE
Is it possible to toggle the value of "disable_brightness_adjust" from the UI?

### DISCUSSION THREAD

**Discussion by ccbell42** [claytonjn/hass-circadian_lighting#240] [General]
I found [this closed issue](https://github.com/claytonjn/hass-circadian_lighting/issues/102) that discusses the same thing, but the solution seems to involve replacing the package entirely with a different one. However, this was also mentioned in the chat:

> As an interim step, would it be possible to add a property parallel to disable_brightness_adjust but for color temperature? Say, disable_ct_adjust? That way, it would be possible to have one circadian switch controlling color temperature and one controlling brightness, apply them to the same lights, and then turn them on and off entirely independently.

> You can already do that, just configure the lights under lights_brightness for the brightness-only switch.

I didn't really understand this answer. @claytonjn Would doing what you mentioned here allow me to add a toggle switch to the UI that turns on/off brightness adjust for a light? If so, would you mind expanding on how to configure this, maybe with an example configuration?

For context, I usually want my lights to automatically adjust their brightness. However, sometimes at night, I need to turn the brightness up. But when I do, I don't want to disable circadian lighting entirely, I just want it to stop overriding my manual brightness setting.

Thanks!

**Comment by claytonjn** [comment]
If you want to have two separate switches to allow for turning on and off color temperature adjusting or brightness adjusting independent of each other the configuration would look something like this:
```yaml
# Enable Circadian Lighting
circadian_lighting:

switch:
# Add Color Temperature Switch
  - platform: circadian_lighting
    lights_ct:
      - light.example_light
    name: Example Color Temperature Circadian Lighting Switch
    disable_brightness_adjust: true
# Add Brightness Switch
  - platform: circadian_lighting
    lights_brightness:
      - light.example_light
    name: Example Brightness Circadian Lighting Switch
```
