### ISSUE TITLE
Suggestion: update circadian switch configuration with service call

### ISSUE THREAD

**Issue by cerebrate** [claytonjn/hass-circadian_lighting#102]
So, for example, I could call 

```
service: circadian_lighting.reconfigure
data:
  entity_id: switch.circadian_lighting_living_room
  disable_brightness_adjust: true
```

to switch off brightness adjust alone, or any other adjustments to, say, min_brightness, max_brightness. or other parameters.

My specific use case is that my wife sometimes works on craft projects in the evening, and as such it would be convenient if there were an easy way to disable the brightness adjustment (dim light being hard on the eyes when working) and keep the color temperature adjustment on those evenings, and revert to having it enabled the rest of the time. At the moment I am emulating this with two circadian lighting switches and automation to make them disable each other when enabled, but this is an ugly kluge.
