### ISSUE TITLE
"invalid_config" errors when trying to use sunrise_time, sunset_time, or sunset_offset config variables

### ISSUE THREAD

**Issue by jtotham** [claytonjn/hass-circadian_lighting#126]
Love your work Clayton, used it since it started out on SmartThings and now on here and it's even better.

I'm running Home Assistant from Docker using Circadian_lighting version 1.0.13 installed via HACS 

When I try and use either, sunrise_time, sunset_time, or sunset_offset config variables in my configuration.yml I get the following errors when I start up HASS

`2020-10-20 10:43:22 ERROR (MainThread) [homeassistant.config] Invalid config for [switch.circadian_lighting]: [sunset_offset] is an invalid option for [switch.circadian_lighting]. Check: switch.circadian_lighting->sunset_offset. (See /config/configuration.yaml, line 35). Please check the docs at https://github.com/claytonjn/hass-circadian_lighting`

`2020-10-20 10:23:04 ERROR (MainThread) [homeassistant.config] Invalid config for [switch.circadian_lighting]: [sunrise_time] is an invalid option for [switch.circadian_lighting]. Check: switch.circadian_lighting->sunrise_time. (See /config/configuration.yaml, line 35). Please check the docs at https://github.com/claytonjn/hass-circadian_lighting `

The section from my configuration.yml for this is:
```
circadian_lighting:
switch:
  - platform: circadian_lighting
    disable_brightness_adjust: false
    #sunrise_time: 07:00:00
    #sunset_time: 21:00:00
    sunset_offset: +03:00:00
    min_brightness: 50
    max_brightness: 100
    sleep_brightness: 1
    sleep_entity: input_boolean.nighttime
    sleep_state: on
    lights_ct:
      - light.hallway
      - light.bedroom
      - light.living_room
      - light.desk
      - light.kitchen
      - light.spare_bedroom
      - light.bathroom
```

I've tried quoting the times in both single and double quotes, using hh:mm and hh:mm:ss and I can't get it to work, am I missing something obvious?

I took a look in the py files and can't see these variables being pulled anywhere, is this a case that the documentation is ahead of the acutal plugin?

Thanks in advance to anyone who can point me in the right direction

**Comment by claytonjn** [comment]
`sunrise_time`, `sunset_time`, and `sunset_offset` are all set at the component level, as described here: https://github.com/claytonjn/hass-circadian_lighting/wiki/Advanced-Configuration because they're universal for _all_ Circadian Lighting switches to keep everything in sync.

Your config should look like:
```yaml
circadian_lighting:
    #sunrise_time: 07:00:00
    #sunset_time: 21:00:00
    sunset_offset: +03:00:00
switch:
  - platform: circadian_lighting
    disable_brightness_adjust: false
    min_brightness: 50
    max_brightness: 100
    sleep_brightness: 1
    sleep_entity: input_boolean.nighttime
    sleep_state: on
    lights_ct:
      - light.hallway
      - light.bedroom
      - light.living_room
      - light.desk
      - light.kitchen
      - light.spare_bedroom
      - light.bathroom
```
