### ISSUE TITLE
Wiki update for Additional-Functionality examples

### ISSUE THREAD

**Issue by cooljimy84** [claytonjn/hass-circadian_lighting#127]
https://github.com/claytonjn/hass-circadian_lighting/wiki/Additional-Functionality

It might be worth including extra examples to use RGB, XY and mireds as well as the normal Kelvin colour temperatures.
something like the below, or even split them out in to separate codes boxes to avoid confusion.
```
action:
  service: light.turn_on
  data_template:
    entity_id: light.entitykelvin
    # above entity is a light that supports colortemp in kelvin
    kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"

action:
  service: light.turn_on
  data_template:
    entity_id: light.entityRGB
    # above entity is a light that supports RGB
   rgb_color:
       - "{{ state_attr('sensor.circadian_values', 'rgb_color') [0] | int }}"
       - "{{ state_attr('sensor.circadian_values', 'rgb_color') [1] | int }}"
       - "{{ state_attr('sensor.circadian_values', 'rgb_color') [2] | int }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"

action:
  service: light.turn_on
  data_template:
    entity_id: light.entityXY
    # above entity is a light that supports XY
   xy_color:
       - "{{ state_attr('sensor.circadian_values', 'xy_color') [0] }}"
       - "{{ state_attr('sensor.circadian_values', 'xy_color') [1] }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"

action:
  service: light.turn_on
  data_template:
    entity_id: light.entityMireds
    # above entity is a light that supports Mireds
    color_temp: "{{ (1000000.0 / state_attr('sensor.circadian_values', 'colortemp')) | round (0) }}"
    brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"
```
