### ISSUE TITLE
How do I verify it's working?

### ISSUE THREAD

**Issue by ultimateguy** [claytonjn/hass-circadian_lighting#128]
Sorry for the basic questions, but I'm having trouble getting this add-on setup. It doesn't appear to be doing anything to any of my lights. I have installed the files and added the following to my config file:

```
circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.kitchen_sink
      - light.kitchen_table
      - light.living_room
      - light.foyer
    lights_rgb:
      - light.rgb_lamp
```

The ones in light_ct are Sengled zigbee bulbs that are non-rgb. The light.rgb_lamp is a Sengled zigbee RGB bulb.

I can see two entities available: sensor.circadian_values and switch.circadian_lighting_circadian_lighting. (I'm not sure why the name repeats itself in the latter?)

I've enabled the logging but I don't see any obvious error messages related to circadian_lighting.
