### ISSUE TITLE
Cannot move lights to a different switch, and deleted switch entities remain

### ISSUE THREAD

**Issue by richardroberts** [claytonjn/hass-circadian_lighting#134]
Hello, thanks for the great work on this integration!  I created a configuration with two switches, as below:

```
adaptive_lighting:
  - name: "nondimming"
    lights:
      - light.bedroom_hallway
      - light.kitchen_cabinet_lights
      - light.kitchen_ceiling
      - light.living_room_window_lamp
      - light.lamp_near_tv
    min_brightness: 100
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 4000
    transition: 45
    interval: 90
  - name: "dimming"
    lights:
       - light.bedroom_floor_lamp
```

Now, I move light.bedroom_floor_lamp from the "dimming" to "nondimming" switch in the config file, but this light continues to be updated as if it were in the "dimming" switch.  Further, if I delete the "dimming" switch from the config file altogether, its entities remain behind, I can see them in the overview dashboard and entity list.  This seems to be a bug?
