### ISSUE TITLE
[HOW-TO] Adding Multiple Switches

### ISSUE THREAD

**Issue by seanmccabe** [claytonjn/hass-circadian_lighting#137]
I've seen it mentioned multiple times that people have multiple switches for Circadian Lighting, however the docs do not state how to do this, and any attempt I make and doing this, does not work.

Wondering if someone can share how to do this, and then perhaps up date the docs.

My yaml below:

```
- platform: circadian_lighting
  name: noBrightness
  sleep_entity: input_boolean.night_mode
  sleep_state: true
  sleep_colortemp: 2500
  sleep_brightness: 5
  disable_brightness_adjust: true
  lights_ct:
    - light.study_lights
    - light.lounge_lamp
- platform: circadian_lighting
  name: withBrightness
  sleep_entity: input_boolean.night_mode
  sleep_state: true
  sleep_colortemp: 2500
  sleep_brightness: 10
  lights_ct:
    - light.upstairs_lamp
```

Many thanks
