### ISSUE TITLE
Use `input_number` values for switches

### ISSUE THREAD

**Issue by kirbo** [claytonjn/hass-circadian_lighting#144]
Hi,
I am stumbling to setting up CL switches in a way that I could use `input_number` values.
This works like a charm:
```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: 2000
  sleep_brightness: 10
  min_brightness: 20
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```
..but I'd like to create separate `input_boolean` slides in my Lovelace UI, so that I could change the values "on-the-fly" without the need of modifying the configuration files.

I've tried all the following, with no luck:
```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: {{ states('input_number.circadian_lighting_sleep_colortemp_ufo') | int }}
  sleep_brightness: {{ states('input_number.circadian_lighting_sleep_brightness_ufo') | int }}
  min_brightness: {{ states('input_number.circadian_lighting_min_brightness_ufo') | int }}
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: "{{ states('input_number.circadian_lighting_sleep_colortemp_ufo') | int }}"
  sleep_brightness: "{{ states('input_number.circadian_lighting_sleep_brightness_ufo') | int }}"
  min_brightness: "{{ states('input_number.circadian_lighting_min_brightness_ufo') | int }}"
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: {{ states('input_number.circadian_lighting_sleep_colortemp_ufo') }}
  sleep_brightness: {{ states('input_number.circadian_lighting_sleep_brightness_ufo') }}
  min_brightness: {{ states('input_number.circadian_lighting_min_brightness_ufo') }}
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: "{{ states('input_number.circadian_lighting_sleep_colortemp_ufo') }}"
  sleep_brightness: "{{ states('input_number.circadian_lighting_sleep_brightness_ufo') }}"
  min_brightness: "{{ states('input_number.circadian_lighting_min_brightness_ufo') }}"
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: {{ states.input_number.circadian_lighting_sleep_colortemp_ufo.state | int }}
  sleep_brightness: {{ states.input_number.circadian_lighting_sleep_brightness_ufo.state | int }}
  min_brightness: {{ states.input_number.circadian_lighting_min_brightness_ufo.state | int }}
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: "{{ states.input_number.circadian_lighting_sleep_colortemp_ufo.state | int }}"
  sleep_brightness: "{{ states.input_number.circadian_lighting_sleep_brightness_ufo.state | int }}"
  min_brightness: "{{ states.input_number.circadian_lighting_min_brightness_ufo.state | int }}"
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: {{ states.input_number.circadian_lighting_sleep_colortemp_ufo.state }}
  sleep_brightness: {{ states.input_number.circadian_lighting_sleep_brightness_ufo.state }}
  min_brightness: {{ states.input_number.circadian_lighting_min_brightness_ufo.state }}
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

```yaml
- name: ufo
  platform: circadian_lighting
  sleep_colortemp: "{{ states.input_number.circadian_lighting_sleep_colortemp_ufo.state }}"
  sleep_brightness: "{{ states.input_number.circadian_lighting_sleep_brightness_ufo.state }}"
  min_brightness: "{{ states.input_number.circadian_lighting_min_brightness_ufo.state }}"
  initial_transition: 0.25
  lights_ct:
    - light.hue_lamp_ufo
```

**Comment by Vonkenboer** [comment]
I use the standard Circadian sensor and switch to extract values to input_number lists (automation). Maybe you can use them to do what you want to achieve. 

My (noob) automation example:
```
alias: Circadian colorTemp Processing
description: ''
trigger:
  - platform: state
    entity_id: sensor.circadian_values
    attribute: colortemp
condition: []
action:
  - service: input_number.set_value
    data_template:
      value: '{{ state_attr("sensor.circadian_values", "colortemp")| round(0) }}'
    target:
      entity_id: input_number.circadian_colortemp
  - service: input_number.set_value
    data_template:
      value: '{{states.sensor.circadian_values.attributes.rgb_color.0 | round(0)}}'
    target:
      entity_id: input_number.circadian_color_redvalue_0_255
  - service: input_number.set_value
    data_template:
      value: '{{states.sensor.circadian_values.attributes.rgb_color.1 | round(0)}}'
    target:
      entity_id: input_number.circadian_color_greenvalue_0_255
  - service: input_number.set_value
    data_template:
      value: '{{states.sensor.circadian_values.attributes.rgb_color.2 | round(0)}}'
    target:
      entity_id: input_number.circadian_color_bluevalue_0_255
  - service: input_number.set_value
    data_template:
      value: >-
        {{states.switch.circadian_lighting_circadian_lighting.attributes.brightness
        | round(0)}}
    target:
      entity_id: input_number.circadian_brightness
  - service: input_text.set_value
    data_template:
      value: >-
        {{states("input_number.circadian_color_redvalue_0_255")|int}},
        {{states("input_number.circadian_color_greenvalue_0_255")|int}},
        {{states("input_number.circadian_color_bluevalue_0_255")|int}}
    target:
      entity_id: input_text.circadian_color_rgbvalue_0_255
mode: single
```
