### ISSUE TITLE
please help configure colortemp

### ISSUE THREAD

**Issue by prankousky** [claytonjn/hass-circadian_lighting#169]
Hi everybody,

I installed the addon and it works great; however, the default `min_colortemp` is too low for my taste. This is from the `Advanced configuration` [page here on github](https://github.com/claytonjn/hass-circadian_lighting/wiki/Advanced-Configuration#component-configuration-variables)

![grafik](https://user-images.githubusercontent.com/11297070/137584222-5cd23ea9-d291-4e15-a709-73d1ace71734.png)

I don't understand this minimum of `1000`. See here
![grafik](https://user-images.githubusercontent.com/11297070/137584251-a0512d5b-d721-412b-a6a7-be8fe74ab875.png)

My light is **currently** at `color_temp: 217`; I would like a minimum of `300` and a maximum of `460`. But these values are way below the minimum.

This is my configuration

```
circadian_lighting:
  min_colortemp: 3000
  max_colortemp: 4600
  interval: 30

switch:
  - platform: circadian_lighting
    name: Wohnzimmer
    initial_transition: 5
    lights_ct:
      - light.wohnzimmer_licht_mitte
      - light.wohnzimmer_licht_vintage
      - light.wohnzimmer_licht_fensterlicht
  - platform: circadian_lighting
    name: Arbeitszimmer
    initial_transition: 5
    lights_ct:
      - light.arbeitszimmer_licht_gruen
      - light.arbeitszimmer_licht_links
 ```

I just added an extra `0` to the min/max values, because I didn't know what else to try. This doesn't seem to work, though. When I do the steps below, the light is still way too cold for my taste.

* turn off `switch.circadian_lighting_arbeitszimmer`
* change `light.arbeitszimmer_licht_links` to a value **way** too warm, simply to see the change when turning on the switch again
* turn on `switch.circadian_lighting_arbeitszimmer`

The light will gradually change the temperature to a too cold value. Can you please tell me what I need to change in order for this to work? Thank you :)
