### ISSUE TITLE
CL and (Xiaomi) Yeelight RGB bulb shenanigans - (also quite possible HW failure)

### ISSUE THREAD

**Issue by gsotiriou** [claytonjn/hass-circadian_lighting#172]
Hi @claytonjn first of, thank you for all your hard work and effort that you (and all the other contributors) have put into this custom component. Highly appreciated! 

Before presenting my issue (which is pretty much summed up in the title - allow me to present what I run and how I run it.

<details><summary>System</summary>

version | core-2021.11.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.60-qnap
arch | x86_64
timezone | Europe/Athens

</details>

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.17.1
Stage | running
Available Repositories | 909
Installed Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 14
views | 9
mode | yaml

</details>

<details><summary>Hardware related to the issue</summary>

Four identical Yeelight RGB Gen2 bulbs and 1 Yeelight RGB Gen1 lightstrip, with fully updated firmware on the European (aka German) Yeelight server.

### configuration.yaml
```yaml
yeelight: !include integrations/yeelight.yaml
```
### integrations/yeelight.yaml
```yaml
devices:
  192.168.1.62:
    name: TV lightstrip
  192.168.1.63:
    name: Armchair lamp
  192.168.1.64:
    name: Shelf lamp
  192.168.1.65:
    name: Floor lamp
  192.168.1.66:
    name: Table lamp
```
</details>

<details><summary>CL configuration</summary>

### configuration.yaml
```yaml
circadian_lighting:
switch: !include_dir_merge_list switches/
```

### switches/circadian_lighting_switches.yaml
```yaml
- platform: circadian_lighting
  name: Living room circadian
  lights_ct:
    - light.floor_lamp
    - light.table_lamp
    - light.armchair_lamp
    - light.tv_lightstrip
    - light.shelf_lamp
```
</details>

# Issues
With the exception of the lightstrip I have faced many different issues with the bulbs above when using the provided configuration of CL. I would also like to highlight that the following issues occur **only** when CL is used and the bulbs (seem to) work fine otherwise.

## Issue No.1 - _The armchair black sheep_
Under "normal" circumstances (to see the definition of ab-normal see below _the pink madness_ issue ), during evening and night times the 3 out of 4 bulbs (`floor` , `table` , `shelf`) have the same hue whereas the 4th (`armchair`) has a way more orange-ish hue, way different than the others. I am not in a position to determine which hue was the correct one, but it is very weird that same bulbs, under the same CL switch/sensor do not seem to produce the same hue and have such a **vast** difference.

_If I had to guess, which the correct hue is, I would say that **the `armchair` hue is the correct one and the other 3 are wrong**. Because I ran CL some years ago with 4 Yeelight **GEN1** bulbs and they all "agreed" on this more orange-like hue._

## Issue No.2 - _The morse code_
Again during evening and night times I can clearly see prolonged moments of my `shelf` and `armchair` flickering intensely. This is quite irritating and tiring for my eyes.

## Issue No.3 - _The pink-stuck madness_
After a specific hour, every day, the `shelf_lamp` turns pink! As time progresses it only gets pinker and pinker. Now here comes the *really weird part*. As long as the bulb is in this (pink-stuck) state (regardless if CL switch is ON or OFF) it will not change color no matter how I command it (via HA), with the exception of green color. So, in that state, blue is pink , red is pink , yellow is pink and the **only exception** is green which produces green - don't ask me why!

This is something that cannot be amended or reverted and the only "solution" is to turn off the lamp, cut the power from it, restart HA  and turn on the lamp, at which point the lamp will assume the "correct" color for some moments but on the next update (assuming CL is ON) it will become pink-stuck again with all the same effects described above.

Another "solution" I recently found to very temporarily fix this issue is to turn off CL and use the official Yeelight application. Using the Yeelight app I turn off the lamp, turn it back on and put it on flow for a while. It will respond much slower at first to the Yeelight app (as if it's ... stuck) but once it starts flowing and changing all possible colors of the rainbow once, then it comes back to normal. Of course if I open CL again, it will become pink-stuck, with all the same effects described above.

I am seriously considering faulty hardware since I searched this repository even in closed tickets and never found something similar. **However** , since the lamp(s) do not produce any of these issues with CL off and (in case of Issue No.3) the lamp is able to assume all possible hues when it is not in this pink-stuck state, I was also wondering if we could consider a possible bug in CL causing the lamp to glitch.

I have enabled logging at the time of writing this and I will be back with as much as I can:
```yaml
logger:
  default: error
  logs:
    custom_components.circadian_lighting: debug
    custom_components.circadian_lighting.sensor: debug
    custom_components.circadian_lighting.switch: debug
```
Let me know if I need to enable anything additionally to help you out - I would really like your feedback on this.
