### ISSUE TITLE
Question: How does one verify that the add-on is working?

### ISSUE THREAD

**Issue by bgshacklett** [claytonjn/hass-circadian_lighting#173]
I've recently installed, and configured, this add-on. I believe I have the configuration set appropriately, but I haven't seen any changes in the lights' color temperatures, nor brightness. That said, I understand that this add-on functions over long time-scales of ~12 hours, so it may be difficult to see whether it's having its intended effect at a glance.

I've looked in the logs at http://homeassistant.local:8123/config/logs, and I'm not seeing any output related to circadian_lighting. I've also enabled debugging and looked through `/config/home-assistant.log`. I see some events, but nothing that really tells me what's happening. Is there anywhere else I can look to get a more timely status of the add-on?

Thanks!

**Comment by claytonjn** [comment]
Can you share your configuration for Circadian Lighting?  With debug logging enabled and at least one CL switch entity turned on you should see log entries every `interval`, which is 5 minutes by default.

**Comment by bgshacklett** [comment]
# configuration.yaml
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

# Enable cloud
cloud:

group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zwave: !include zwave.yaml

# Enable Circadian Lighting
# https://github.com/claytonjn/hass-circadian_lighting
circadian_lighting:
switch: !include circadian_lighting.yaml

logger:
  logs:
    custom_components.circadian_lighting: debug
    custom_components.circadian_lighting.sensor: debug
    custom_components.circadian_lighting.switch: debug
```

# circadian_lighting.yaml
```
  - platform: circadian_lighting
    name: Circadian Lighting
    lights_ct:
      - light.family_room_front_led_lamp_1
      - light.family_room_front_led_lamp_2
      - light.family_room_rear_led_lamp_1
      - light.kitchen_led_lamp_1
      - light.kitchen_led_lamp_2
      - light.kitchen_led_lamp_3
      - light.kitchen_led_lamp_4
      - light.kitchen_led_lamp_5
      - light.kitchen_led_lamp_6
      - light.kitchen_led_lamp_7
```
