### ISSUE TITLE
Two instances of circadian light or two switches

### ISSUE THREAD

**Issue by Sergiodiaz53** [claytonjn/hass-circadian_lighting#191]
Hello

I just started using Circadian lights and it is an amazing component!
I was wondering if there is anyway to have two different instances and/or two different switches.

The reason is because I want to use regular circadian lights in my home office, but I want to
a) limit color temp in the bedroom
or
b) turn of the switch for circadian lights assigned to the bedroom and set a custom scene via automation

Could this be achieved with the current state of the component?

Thanks in advance.

**Comment by shalva-an** [comment]
You can add it in your configuration.yaml; This is how I have mine:
```
circadian_lighting:

switch:
  - platform: circadian_lighting
    name: Bed Light Auto
    lights_ct:
      - light.bed_lights
  - platform: circadian_lighting
    name: Kitchen Lights Auto
    lights_ct:
      - light.kitchen
```

Check out https://github.com/RobertDWhite/home-assistant/blob/master/switch/circadian_lighting.yaml for more examples

**Comment by koshisan** [comment]
Is it possible that this is broken in some way? I am new to Home Assistant, so I don't want to rule out an error on my side, but I have this in my configuration.yaml:

circadian_lighting: 
# Example configuration.yaml entry
switch:
  - platform: circadian_lighting
    name: "CircadianLightsOG1"
    lights_ct:
      - light.decke_essbereich
      - light.decke_kueche
      - light.decke_buro

  - platform: circadian_lighting
    name: "CircadianLightBath"
    disable_brightness_adjust: true
    lights_ct:
      - light.decke_schreibtisch

And yet the second switch never seems to appear anywhere...

**Comment by claytonjn** [comment]
Closing as this is already possible, I should have cleaned this up last year.

**Comment by kl4ppdrachen** [comment]
Is there a way to add two instances? The problem is, I creaded a instance with a `max_colortemp = 6500k` but one of my lights can only handle `4000k`.

As Example:
```
#Circadian
circadian_lighting:
    min_colortemp: 2000
    max_colortemp: 6500
circadian_lighting:
    min_colortemp: 2000
    max_colortemp: 4000
```

or something like this:
```
switch:
  - platform: circadian_lighting
    name: Bed Light Auto
    max_colortemp: 6500
    lights_ct:
      - light.bed_lights
  - platform: circadian_lighting
    name: Kitchen Lights Auto
    max_colortemp: 4000
    lights_ct:
      - light.kitchen
```
