### ISSUE TITLE
Deleted switches are not removed

### ISSUE THREAD

**Issue by eikowagenknecht** [claytonjn/hass-circadian_lighting#211]
I started configuring the integration like this:

```yaml
circadian_lighting:

switch:
  - platform: circadian_lighting
    lights_ct:
      - light.eg_essen_hue_decke
      - light.eg_buero_hue_decke
```

Did a reboot and the switch showed up, named `switch.circadian_lighting_circadian_lighting`.

I later organized the switches into rooms:

```yaml
switch:
  - platform: circadian_lighting
    name: Circadian EG.Essen
    lights_ct:
      - light.eg_essen_hue_decke

  - platform: circadian_lighting
    name: Circadian EG.Büro
    lights_ct:
      - light.eg_buero_hue_decke
```

and after a reboot room specific sensors showed up. But the old one (`switch.circadian_lighting_circadian_lighting`) stays. How do I get rid of that?

Trying to switch it on or off I just get an error

```
Logger: homeassistant.helpers.service
Source: helpers/service.py:637
First occurred: 12:24:38 (2 occurrences)
Last logged: 12:24:51

Unable to find referenced entities switch.circadian_lighting_circadian_lighting or it is/they are currently not available
```
