### ISSUE TITLE
custom_updater - help

### ISSUE THREAD

**Issue by mrplow** [claytonjn/hass-circadian_lighting#22]
Thanks for this great project. I've been using it for a few months with great success.

I believe I have my configuration.yaml setup mostly correct with the custom_update but I don't see a way of updating except for manually triggering custom_updater.update_all

Am I missing something?

```
# Custom Updater
custom_updater:
  track:
    - cards
    - components
  component_urls:
    - https://raw.githubusercontent.com/claytonjn/hass-circadian_lighting/master/custom_updater.json
```

Thanks again
