### ISSUE TITLE
Transition values not working

### ISSUE THREAD

**Issue by nicholaskillin** [claytonjn/hass-circadian_lighting#223]
I don't know if I'm doing something wrong or if there is a bug, but I can't seem to increase the amount of time it takes to transition from one color to another.

Here is my current config:
```yml
circadian_lighting:
  interval: 10
  transition: 30

switch:
  - platform: circadian_lighting
    initial_transition: 30
    lights_ct:
       - light.office_light
```

The component is working generally. The light was left on and slowly changed color temp throughout the day. 

However with this config if I intentionally change the color temperature of the light, then turn the light off with a physical non-smart switch, wait for a few seconds, and then turn it on again, I do see the light transition back to the correct color temperature within a couple of seconds, but the transition itself happens in about 1 second.

Any ideas what I might be doing wrong or misunderstanding about the configuration options?

**Comment by TheRealBenForce** [comment]
This happens to me to with all my devices and light groups. Did you ever figure it out? 

```
circadian_lighting:
switch:
  - platform: circadian_lighting
    initial_transition: 10
    lights_ct:
       - light.kitchen
     disable_entity: light.kitchen
     disable_state: unavailable
```
