### ISSUE TITLE
Does this work on `service: scene.` ?

### ISSUE THREAD

**Issue by Gil80** [claytonjn/hass-circadian_lighting#235]
Does this work on scenes too?

This is what I have:
```
action:
  - choose:
        - conditions:
               - condition: template
                  value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
              - service: scene.turn_on
                 target:
                    entity_id: scene.evning_light_color
                 metadata: {}
```

Will this work if I set it up like this?

```
action:
  - choose:
        - conditions:
               - condition: template
                  value_template: "{{ trigger.to_state.state == 'on' }}"
          sequence:
              - service: scene.turn_on
                 target:
                    entity_id: scene.evning_light_color
                    data_template:
                    entity_id: light.entity
                    kelvin: "{{ state_attr('sensor.circadian_values', 'colortemp') | int }}"
                   brightness_pct: "{{ state_attr('switch.circadian_lighting_[...]', 'brightness') | int }}"
                 metadata: {}
```
