### ISSUE TITLE
Circadian Lighting not setting Color Temperature of Xiaomi Desk Lamp

### ISSUE THREAD

**Issue by jkms** [claytonjn/hass-circadian_lighting#44]
I have a [Xiaomi Desk Lamp](https://www.mi.com/global/smartlamp) setup in HomeAssistant, and it's working as expected:

![image](https://user-images.githubusercontent.com/660916/66367447-06f33f80-e949-11e9-8f84-9866ca595b67.png)

Curiously, although I can configure the brightness and color temperature via Home Assistant, the circadian lighting component does **not** adjust colour temperature (but brightness works).  In fact, it seems to generate the following error:

```
2019-10-07 21:11:46 ERROR (SyncWorker_12) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:11:46 ERROR (SyncWorker_5) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:15:15 ERROR (SyncWorker_6) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:15:15 ERROR (SyncWorker_18) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:15:17 ERROR (SyncWorker_16) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:15:19 ERROR (SyncWorker_16) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
2019-10-07 21:15:48 ERROR (SyncWorker_8) [homeassistant.components.yeelight.light] Error when calling <function YeelightGenericLight.set_colortemp at 0x6ed219c0>: {'code': -5000, 'message': 'general error'}
```

I have a number of Yeelight bulbs and Milight bulbs (using [Sidoh's Milight Hub](https://github.com/sidoh/esp8266_milight_hub)) controlled using Circadian Lighting and working as expected.  Only the Desk Lamp doesn't work.

### Configuration.yaml
```
circadian_lighting:
  min_colortemp: 1900
  max_colortemp: 4000
  interval: 30
  transition: 10
```
```
yeelight:
  devices:
      192.168.1.188: # <----- Working bulb
        name: Hallway
        transition: 1000
      192.168.1.182: # <----- Trouble Lamp
        name: Desk Lamp
        transition: 1000
```
```
switch:
  - platform: circadian_lighting
    name: Main
    min_brightness: 20
    max_brightness: 80
    sleep_colortemp: 1000
    sleep_brightness: 1
    sleep_entity: input_boolean.sleepy_time
    sleep_state: "on"
    lights_ct:
      - light.Desk_Lamp
      - light.Hallway
```

### Maybe also useful?
![image](https://user-images.githubusercontent.com/660916/66367792-82092580-e94a-11e9-9e27-9852c54bb74e.png)
![image](https://user-images.githubusercontent.com/660916/66367820-9d743080-e94a-11e9-9c9f-fcd145e6ddec.png)

**Comment by jkms** [comment]
I will check when I get home tonight.  Though, without checking, I can confirm that Circadian does **not** adjust the lamp temperature to it's maximum if the Circadian temperature is too warm, which is the behavior I would have expected.

I will set the range to 3000-6000 and test tonight.

**Comment by claytonjn** [comment]
> I can confirm that Circadian does **not** adjust the lamp temperature to it's maximum if the Circadian temperature is too warm, which is the behavior I would have expected.

This is the behavior I would expect as well - this is what happens with my Hue lights, but come to think of it, that's a result of the Hue API and _not_ Home Assistant implementation. 

So assuming this is the issue, the question is; should CL check the min/max mireds of every light every time an adjustment is sent to ensure it doesn't send a value outside that range, or should it be up to the user to configure the min_colortemp and max_colortemp appropriately so that CL doesn't need to query device attributes every adjustment.

**Comment by jkms** [comment]
> or should it be up to the user to configure the min_colortemp and max_colortemp appropriately so that CL doesn't need to query device attributes every adjustment.

But then the user (me :P) would need to create different CL switches and settings for different groups of lights.

**Comment by claytonjn** [comment]
Actually, because color temperature is at the platform level not the switch level you're currently restricted to the lowest-common-denominator range for all lights. For that reason I'm leaning towards CL doing the attribute query...I just hate the idea of that extra overhead.

**Comment by Joshfindit** [comment]
Not that this helps reduce the overhead but how about a simple “if temp to be set > lamp_max, set to lamp_max” and the same on the cool spectrum.

Hass (I feel) needs to expand to do things like automatically handling mix/max on all values, as well as custom curves and mappings (such as if a lamp has 3 brightnesses, specify the range that triggers each). That way addons can simplify.

**Comment by claytonjn** [comment]
> Not that this helps reduce the overhead but how about a simple “if temp to be set > lamp_max, set to lamp_max” and the same on the cool spectrum.

That's basically what I was thinking, but finding lamp_max would require querying the max_mireds attribute.

**Comment by TravelinMax** [comment]
> should CL check the min/max mireds of every light every time an adjustment is sent to ensure it doesn't send a value outside that range
I would hella love this!

**Comment by jkms** [comment]
Okay, changing my config worked:
```
circadian_lighting:
#  min_colortemp: 1900 # <--- Old Value
  min_colortemp: 3000 # <--- New Value
  max_colortemp: 4000
  interval: 30
  transition: 10
```
So you were right about the problem.


>Not that this helps reduce the overhead but how about a simple “if temp to be set > lamp_max, set to lamp_max” and the same on the cool spectrum.

Is this something I should be putting in my config somewhere?  or are you talking CL code here?
