### ISSUE TITLE
question about disabling circadian lighting

### ISSUE THREAD

**Issue by mikeage** [claytonjn/hass-circadian_lighting#51]
Hi, I just discovered this component and I love it! That said, having said that, I sometimes might not want to use it :-)

If I'm writing an automation to manually adjust brightness or color temperature, I can turn off the switch for CL. I also know there is a `disable_entity` and `disable_state` option that I can use to monitor another entity. But is there any way to intercept a change to, say, brightness that is done via the Alexa integration in HA and use that to tell CL to stop controlling a particular light? If someone explicitly sets the light configuration, it's a pretty good sign that they want control (probably with a timeout; that's for later), and not have the automatic CL.

**Comment by claytonjn** [comment]
To my knowledge, there's no way of knowing if an adjustment was made by another integration, the frontend, or Circadian Lighting itself. If I'm mistaken, hopefully someone can share.

If I get time to implement #1 that may work for you, otherwise the best thing for your example may be to expose the CL switches to Alexa and say something like "Alexa, Turn off CL and set brightness to 50%".

**Comment by TravelinMax** [comment]
How about an automation like this:
trigger: state change of your lights
condition: color and brightness of lights doesn't equal color and brightness of CL component AND light is not off (so you don't turn off CL when you turn off a light)
action: turn off CL

You might have to add a delay before you check the color and brightness if your lights don't turn on to the right color immediately. You also might have to add a range to the color and brightness check (within 1 or 2%).

**Comment by mikeage** [comment]
Clever. It has to be quicker than the CL auto adjust, though. Might also want to try to avoid the case of off->on, and only catch on->on (I e., change), but this might just work! Thanks :)

**Comment by mikeage** [comment]
Ok, I just about have this working. One problem I have is that when CL is enabled, it sometimes may make several distinct changes on the way to the target brightness and color temperature (haven't checked, but I suspect this is color and brightness together). One way to solve this might be with a delay; another is to reenable if they get too close. The delay isn't an option if you use a condition. I'm not sure if I can put an explicit test in an action; I can use a template to see which values I send, but not, I think, if I call a service at all. Need to read up on that...

**Comment by TravelinMax** [comment]
Did you see the post about canceling the new or already running instance of an automation in that threat you linked?

**Comment by mikeage** [comment]
So first of all, I'm an idiot :-) The two changes I was seeing was because I'm toggling a light group... with two bulbs. Didn't dawn on me until I started looking at the CL logs that it'd toggle the lights individually; the first arrived when only one light had changed, so the group's change was effectively half (the average...) of what it desired. Anyway...

I did see the link, and I'm using it now (there's a typo there; `service.cancel` should be `service.turn_off`). I chose to cancel the first and use the second, figuring that if it needs a delay, best to use the delay after the last change. In any case, it seems like 5 seconds is far too much, but that's all right for now. 

Ideally, though, I'd love if there was some way to have both scripts run to completion. The reason is that I want to template this and apply it to a bunch of lights and groups, and if I change multiple lights in close succession, canceling the script for light 1 just because light 2 changed isn't the right thing to do. But worst case, copy paste. 

Here's what I'm using now (slightly improved over the original, where I use an `input_select` to have a tristate "On / Temporarily Off / Off" for CL rather than just On/Off. This will let me reset it as needed if there was a manual override (maybe on the next off, maybe after 60 minutes, maybe the next day, whatever):

configuration.yaml
```yaml
switch:
  - platform: circadian_lighting
    name: parents_room
    lights_ct:
      - light.yeelight_ct2_7c49eb1a8ee6
      - light.yeelight_ct2_7c49eb1a8f09

input_select:
  circadian_lighting_parents_room:
    name: Circadian Lighting Parents Room
    options:
      - 'On'
      - 'Overridden'
      - 'Off'
    icon: mdi:theme-light-dark
```
automation.yaml (still has some debug left in)
```yaml
- id: cl_disable_parents
  alias: 'Disable Circadian Light on manual change'
  trigger:
    platform: state
    entity_id: light.parents_room_lights
  condition:
  - condition: state
    entity_id: switch.circadian_lighting_parents_room
    state: 'on'
  - condition: template
    value_template: "{{ trigger.from_state.state == 'on' }}"
  - condition: template
    value_template: "{{ trigger.to_state.state == 'on' }}"
  action:
  - service: script.turn_off
    entity_id: script.cl_disable_parents
  - service: script.cl_disable_parents
    data_template:
      trigger_to_state_object_id: "{{ trigger.to_state.object_id }}"

- id: cl_disable_parents_internal
  alias: 'Disable Circadian Light on manual change (internal)'
  trigger:
  - platform: state
    entity_id: input_select.circadian_lighting_parents_room
  action:
  - service_template: "switch.{% if is_state('input_select.circadian_lighting_parents_room', 'Off') or is_state('input_select.circadian_lighting_parents_room', 'Overridden') %}turn_off{% else %}turn_on{% endif %}"
    data:
      entity_id: switch.circadian_lighting_parents_room
```
script.yaml:
```yaml
cl_disable_parents:
  alias: Disable Circadian Lighting Parents Room
  sequence:
  - service: system_log.write
    data_template:
        # Replace light with a string, because the trigger pased is a string, not an object
      message: "CL Disable triggered. Comparisons will be: {{ ((1000000 / states['light'][trigger_to_state_object_id].attributes.color_temp) | int) }} -  {{ state_attr('sensor.circadian_values', 'colortemp') }} and {{ ((100 * states['light'][trigger_to_state_object_id].attributes.brightness / 255) | int) }} - {{ state_attr('switch.circadian_lighting_parents_room', 'brightness') }}. Now waiting"
      level: info
  - delay: 00:00:05
  - service: system_log.write
    data_template:
      message: "After the delay. Comparisons are: {{ ((1000000 / states['light'][trigger_to_state_object_id].attributes.color_temp) | int) }} -  {{ state_attr('sensor.circadian_values', 'colortemp') }} and {{ ((100 * states['light'][trigger_to_state_object_id].attributes.brightness / 255) | int) }} - {{ state_attr('switch.circadian_lighting_parents_room', 'brightness') }}. Now checking..."
      level: info
  - condition: or
    conditions:
    - condition: template
      value_template: "{{ (((1000000 / states['light'][trigger_to_state_object_id].attributes.color_temp) | int) - state_attr('sensor.circadian_values', 'colortemp')) | abs > 200 }}"
    - condition: template
      value_template: "{{ (((100 * states['light'][trigger_to_state_object_id].attributes.brightness / 255) | int) - state_attr('switch.circadian_lighting_parents_room', 'brightness')) | abs > 5 }}"
  - service: input_select.select_option
    data:
      entity_id: input_select.circadian_lighting_parents_room
      option: "Overridden"
```
