### ISSUE TITLE
Feature Request: Disable Cir. Lightning inside automation

### ISSUE THREAD

**Issue by poudenes** [claytonjn/hass-circadian_lighting#79]
Hi There,

Great Add-ON !!! Use it for all my lights!
Only thing when I turn on a light with a specific kelvin or color the cir. lighting react on it.

Would be nice to have a feature that you can add to a action something like this

**circadian: false**

```
  action:
    service: light.turn_on
    data:
      entity_id: light.bedroom_all
      kelvin: 2800
      brightness_pct: 100
      circadian: false
```
