### ISSUE TITLE
Breaks transitions when turning lights on

### ISSUE THREAD

**Issue by oxan** [claytonjn/hass-circadian_lighting#82]
I've a few scripts that turn lights on with a transition, e.g.
```
service: light.turn_on
entity_id: light.living_space_lights
data:
  brightness: 255
  transition: 900
```
(I have disabled the brightness adjustment in circadian lighting)

Unfortunately, the circadian lighting breaks the transition, since it immediately issues another `light.turn_on` call without a transition, which overrides the transition I just supplied.

**Comment by claytonjn** [comment]
As far as I know there's nothing that can be done about this. You would just have to disable Cl before turning on with a transition.

**Comment by oxan** [comment]
Yeah, I was afraid so :(

However, I had another idea (without looking too much at the code). I can of course set the initial color temperature myself using the sensor:
```yaml
service: light.turn_on
entity_id: light.living_space_lights
data:
  brightness: 255
  transition: 900
data_template:
  kelvin: "{{ state_attr('sensor.circadian_values', 'color_temp') }}"
```
Would it be possible for CL to detect whether the colortemp is already correct (based on the current state of the light) and if so not issuing another `light.turn_on` command? That'd still override the transition if the color temperature changes during the transition, but I can live with that.

Btw, thanks for your work on this component! It's a really nice feature, and even without transitions this works much better than the homegrown automation-based spaghetti I used before!
