### ISSUE TITLE
Are min/max colour temps and brightness per switch/light possible?

### ISSUE THREAD

**Issue by iamcagn** [claytonjn/hass-circadian_lighting#91]
I have a couple of different brands of bulbs, and it's rare that the colour temps match. I was previously using the native flux intergatrion, but I perfer how this is configured as well as the fact they don't try to control bulbs that are off.

To address the colour temp differences, I had different bulbs set up with Flux with different colour temp ranges. I can see that you provide min_colortemp and max_colortemp at a global setting, but is it possible to set it per bulb? If not, would it be something you consider adding?

**Comment by markianwallace** [comment]
I'd also like help with this.

**Comment by coolinx** [comment]
To be able to have different settings per light group would be great!
While reading the FAQ I saw this mentioning **switch(es)**:

> Circadian Lighting has two main components, a sensor and switch(es). The sensor maintains the calculated color temperature to keep all lights in sync, while the switch(es) allow for specific options to be set for specific groups of lights.

So would that mean you can configure multiple of these switches with each a different set of lights and different settings?

**Comment by claytonjn** [comment]
> So would that mean you can configure multiple of these switches with each a different set of lights and different settings?

You can have multiple switches with different settings (or if you just want to turn CL adjustment on/off for a subset of lights at a time) but color temperature cannot be changed on a switch by switch basis. I'll probably add this ability at some point.

**Comment by iamcagn** [comment]
It would be nice to have profiles of sorts. An example would be:

circadian_lighting:
  - profile: lifx
    max_colortemp: 4400
    sunset_offset: 01:00:00
    interval: 900
    transition: 2
  - profile: hue
    max_colortemp: 4200
    sunset_offset: 00:45:00
    interval: 500
    transition: 5

You could then call the profile on the switch:
switch:
- platform: circadian_lighting
  name: Bedroom 1
  profile: lifx
  lights_ct: light.bedroom_1
- platform: circadian_lighting
  name: Bedroom 2
  profile: hue
  lights_ct: light.bedroom_2

This would also allow you to only need to update all the settings in one location, as well as could be used for other reasons, such as different rooms having different settings, like allowing the bedroom and lounge room lights to dim, while leaving the kitchen and bathroom lights with their default brightness. I know brightness can already be done on a per-light basis, but it would centralize the settings in a single block.

**Comment by basnijholt** [comment]
@iamcagn, I have started implementing the light profiles you suggested in https://github.com/claytonjn/hass-circadian_lighting/pull/114/.

**Comment by iamcagn** [comment]
> @iamcagn, I have started implementing the light profiles you suggested in #114.

That's awesome, thank you so much. I've been trying to hack something together using template sensors but being able to do it with this component will be so much easier.

**Comment by markianwallace** [comment]
Fantastic news.

**Comment by basnijholt** [comment]
@markianwallace and @iamcagn, could you guys try the code of #114?

It works like this:
```yaml
circadian_lighting:
  - profile: default
    min_colortemp: 2000
    interval: 30
  - profile: early
    min_colortemp: 3000
    interval: 10
    sunset_time: "16:00:00"
```

and
```yaml
switch:
  - platform: circadian_lighting
    profile: early  # <----------------profile
    lights_rgb:
      - light.philips_go
      - light.bamboo
      - light.ceiling_bedroom
      - light.lampan
      - light.bed_led
      - light.bed_reading_up
      - light.bed_reading_down
      - light.ceiling_bathroom
      - light.toilet
      - light.ceiling_kitchen
    lights_ct:
      - light.stairs_up
      - light.stairs_down
      - light.hall_1
      - light.hall_2
      - light.hall_3
    sleep_entity: input_select.sleep_mode
    sleep_state: total
    disable_entity: input_select.sleep_mode
    disable_state: half
    min_brightness: 70
    initial_transition: 0
    only_once: true
```
