### ISSUE TITLE
While in Sleep mode, switching back to "normal" colortemp

### ISSUE THREAD

**Issue by rosch100** [claytonjn/hass-circadian_lighting#94]
While sleep mode is enabled at night and the lights receive another trigger to turn on, the color changes to normal night colors even though the sleep_mode setting did not change.

I have set up my lights to turn on/off via motion sensors. So, it is not uncommon for the lights to receive another turn on trigger at night.

Since I use your suggested template 
kelvin: `'{{ state_attr(''sensor.circadian_values'', ''colortemp'') | int }}'`, could it be that the sensor.circadian_values does not change to sleep mode colortemp?

My config:
configuration.yaml
```
circadian_lighting:
  min_colortemp: 2000
  max_colortemp: 6500
  sunrise_offset: -00:00:00

switch:
  - platform: circadian_lighting
    name: Mit Helligkeit
    sleep_colortemp: 5000
    sleep_brightness: 1
    sleep_entity: input_boolean.circadian_sleepmode
    sleep_state: "on"
    lights_ct:
      - light.lampe_schlafzimmer_dach_light
      - light.lampe_schlafzimmer_bett_light  

input_boolean:
  circadian_sleepmode:
    name: Licht Nachtmodus
    initial: off
    icon: mdi:moon-waning-crescent 
```   
automations.yaml
```
- id: '1586430819624'
  alias: Licht im Schlafzimmer einschalten
  description: ''
  trigger:
  - device_id: f160509cd5154058bf9222d7bdfa84db
    domain: binary_sensor
    entity_id: binary_sensor.bewegung_schlafzimmer_occupancy
    platform: device
    type: motion
  condition: []
  action:
  - service: light.turn_on
    data_template:
      kelvin: '{{ state_attr(''sensor.circadian_values'', ''colortemp'') | int }}'
      brightness_pct: '{{ state_attr(''switch.circadian_lighting_mit_helligkeit'',
        ''brightness'') | int }}'
      entity_id:
      - light.lampe_schlafzimmer_bett_light
      - light.lampe_schlafzimmer_dach_light
```
